version: '3'

services:
#-------------------------------------

  mysql:
    build:
      context: mysql
    volumes:
      - mango-mysql-db:/var/lib/mysql
      - ./project-data:/usr/src/app/

#    ports:
#      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
    networks:
      mango_net:
        ipv4_address: 172.29.1.2

#-------------------------------------

  django:

    build:
      context: django

    volumes:
      - ./project-data:/usr/src/app/

    ports:
      - "9000:9000"


    entrypoint: 
      - /bin/sh
      - /usr/src/app/django/startup.sh

    depends_on:
      - mysql
      
    networks:
      mango_net:
        ipv4_address: 172.29.1.4

#-------------------------------------

  nginx:
    build:
      context: nginx
    volumes:
      - ./project-data:/usr/src/app/
    ports:
      - "80:80"
    depends_on:
      - django
    networks:
      mango_net:
        ipv4_address: 172.29.1.6
#-------------------------------------

networks:
  mango_net:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16
volumes:
  mango-mysql-db: 
    external : yes    
