version: '3'

services:
#-------------------------------------

  mysql:
    build:
      context: mysql
    volumes:
      - mango-mysql-db:/var/lib/mysql
      - ./project-data:/usr/src/app/

    ports:
      - "2306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
#-------------------------------------

  angular:
    build:
      context: angular
    volumes:
      - ./project-data:/usr/src/app/
    entrypoint: 
      - /bin/sh
      - /usr/src/app/angular/startup.sh
        
 #-------------------------------------

  django:

    build:
      context: django

    volumes:
      - ./project-data:/usr/src/app/

    ports:
      - "9000:9000"


    entrypoint: 
      - /bin/sh
      - /usr/src/app/django/startup.sh

    depends_on:
      - mysql
      - angular


#-------------------------------------

        #nginx
        #   build:
        #      context: nginx
        #    volumes:
        #      - ./project-data:/usr/src/app/
        #   ports:
        #     - "80:80"
        #   depends_on:
        #     - django
#-------------------------------------

#  sentry:
#    build:
#      context: sentry
 #   volumes:
  #    - ./project-data:/usr/src/app/
#    entrypoint:
#      - /bin/sh
#      - /usr/src/app/sentry/startup.sh
#    depends_on:
#      - mysql
#    networks:
#      mcsap_net:
#        ipv4_address: 172.28.1.7
#-------------------------------------
#  mongo:
#    image: mongo
#    restart:  always
#    networks:
#      mcsap_net:
#        ipv4_address: 172.28.1.8


volumes:
  mango-mysql-db: 
    external : yes    
