# Generated by Django 2.2.6 on 2019-11-16 03:23

import datetime
from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency', models.CharField(max_length=30)),
                ('contact', models.CharField(blank=True, max_length=30)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('fax', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['agency'],
            },
        ),
        migrations.CreateModel(
            name='CurrentLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('log', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateName', models.CharField(max_length=512)),
                ('number', models.CharField(max_length=100)),
                ('date_created', models.DateField(auto_now=True)),
                ('date_sent', models.DateField(default=datetime.date(2010, 1, 1))),
                ('date_paid', models.DateField(default=datetime.date(2010, 1, 1))),
                ('text_record', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RateHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('descr', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='RoomInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=5)),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('pool_deluxe', 'Pool Deluxe'), ('lanai', 'Lanai'), ('presidential', 'Presidential'), ('manor', 'Manor'), ('suites', 'Suites'), ('garden', 'Garden')], max_length=25)),
                ('beds', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('connect', models.CharField(blank=True, max_length=5)),
                ('notes', models.TextField(blank=True)),
                ('current', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Rsvn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('notconfirmed', 'Not Confirmed'), ('confirmed', 'Confirmed'), ('checkin', 'Checking In'), ('checkout', 'Checking Out'), ('notpaid', 'Not Paid'), ('prepaid', 'Prepaid'), ('cancel', 'Cancel'), ('noshow', 'No Show')], max_length=13)),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('source', models.CharField(choices=[('local_fit', 'Local FIT'), ('tour', 'Tour Agency'), ('fit', 'Tour FIT'), ('govt', 'Government'), ('promo', 'Promotional'), ('rack', 'Rack Rate')], max_length=20)),
                ('phone1', models.CharField(max_length=20)),
                ('phone2', models.CharField(blank=True, max_length=20)),
                ('dateIn', models.DateField()),
                ('dateOut', models.DateField()),
                ('rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('pool_deluxe', 'Pool Deluxe'), ('lanai', 'Lanai'), ('presidential', 'Presidential'), ('manor', 'Manor'), ('suites', 'Suites'), ('garden', 'Garden')], max_length=15)),
                ('beds', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('adult', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('child', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('infant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('confirm', models.CharField(blank=True, max_length=20)),
                ('clerk', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('season', models.CharField(choices=[('high', 'High Season'), ('low', 'Low Season'), ('peak', 'Peak Season')], max_length=40)),
                ('beginDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SideEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('pax', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descr', models.TextField()),
                ('venue', models.CharField(choices=[('pool', 'Swimming Pool'), ('confroom2', 'Conference 2nd'), ('confroom3', 'Conference 3rd'), ('cafe', 'Cafe'), ('vcourt', 'Volleyball Court'), ('lobby', 'Lobby'), ('back', 'Back Space'), ('other', 'Other')], max_length=90)),
                ('dateStart', models.DateField()),
                ('timeStart', models.TimeField(default='00:00:00')),
                ('dateEnd', models.DateField()),
                ('timeEnd', models.TimeField(default='00:00:00')),
            ],
            options={
                'ordering': ['-dateStart'],
            },
        ),
        migrations.CreateModel(
            name='WebRsvn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=30)),
                ('lastname', models.CharField(max_length=30)),
                ('phone1', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('dateIn', models.DateField()),
                ('dateOut', models.DateField()),
                ('rooms', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('type', models.CharField(max_length=15)),
                ('beds', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('adult', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('child', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('infant', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('city', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(max_length=30)),
                ('inquiry', models.CharField(blank=True, max_length=20)),
                ('rsvn', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrive_flight', models.CharField(blank=True, max_length=30)),
                ('arrive_time', models.DateTimeField()),
                ('depart_flight', models.CharField(blank=True, max_length=30)),
                ('depart_time', models.DateTimeField()),
                ('promo', models.TextField(blank=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Agent')),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.BooleanField(default=False)),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('from_airport', models.BooleanField(default=False)),
                ('to_airport', models.BooleanField(default=False)),
                ('dailymaid', models.BooleanField(default=False)),
                ('mango', models.BooleanField(default=False)),
                ('extrabed', models.BooleanField(default=False)),
                ('crib', models.BooleanField(default=False)),
                ('connect', models.BooleanField(default=False)),
                ('earlyin', models.BooleanField(default=False)),
                ('lateout', models.BooleanField(default=False)),
                ('event', models.BooleanField(default=False)),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gridColor', models.CharField(choices=[('White', 'White'), ('Burlywood', 'Burlywood'), ('Red', 'Red'), ('Cyan', 'Cyan'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('RoyalBlue', 'RoyalBlue'), ('Orchid', 'Orchid'), ('NavajoWhite', 'NavajoWhite'), ('Maroon', 'Maroon'), ('Sienna', 'Sienna'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('DarkKhaki', 'DarkKhaki'), ('Salmon', 'Salmon'), ('SeaGreen', 'SeaGreen'), ('OrangeRed', 'OrangeRed'), ('YellowGreen', 'YellowGreen'), ('DarkCyan', 'DarkCyan'), ('Black', 'Black'), ('HotPink', 'HotPink'), ('Gray', 'Gray'), ('Coral', 'Coral'), ('SaddleBrown', 'SaddleBrown'), ('SlateBlue', 'SlateBlue')], default='white', max_length=15)),
                ('rsvnColor', models.CharField(choices=[('White', 'White'), ('Burlywood', 'Burlywood'), ('Red', 'Red'), ('Cyan', 'Cyan'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('RoyalBlue', 'RoyalBlue'), ('Orchid', 'Orchid'), ('NavajoWhite', 'NavajoWhite'), ('Maroon', 'Maroon'), ('Sienna', 'Sienna'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('DarkKhaki', 'DarkKhaki'), ('Salmon', 'Salmon'), ('SeaGreen', 'SeaGreen'), ('OrangeRed', 'OrangeRed'), ('YellowGreen', 'YellowGreen'), ('DarkCyan', 'DarkCyan'), ('Black', 'Black'), ('HotPink', 'HotPink'), ('Gray', 'Gray'), ('Coral', 'Coral'), ('SaddleBrown', 'SaddleBrown'), ('SlateBlue', 'SlateBlue')], default='white', max_length=15)),
                ('extraColor', models.CharField(choices=[('White', 'White'), ('Burlywood', 'Burlywood'), ('Red', 'Red'), ('Cyan', 'Cyan'), ('Blue', 'Blue'), ('Green', 'Green'), ('Orange', 'Orange'), ('RoyalBlue', 'RoyalBlue'), ('Orchid', 'Orchid'), ('NavajoWhite', 'NavajoWhite'), ('Maroon', 'Maroon'), ('Sienna', 'Sienna'), ('Yellow', 'Yellow'), ('Purple', 'Purple'), ('DarkKhaki', 'DarkKhaki'), ('Salmon', 'Salmon'), ('SeaGreen', 'SeaGreen'), ('OrangeRed', 'OrangeRed'), ('YellowGreen', 'YellowGreen'), ('DarkCyan', 'DarkCyan'), ('Black', 'Black'), ('HotPink', 'HotPink'), ('Gray', 'Gray'), ('Coral', 'Coral'), ('SaddleBrown', 'SaddleBrown'), ('SlateBlue', 'SlateBlue')], default='white', max_length=15)),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='RsvnBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now=True)),
                ('desc', models.TextField()),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(blank=True, max_length=512)),
                ('roomstatus', models.CharField(blank=True, choices=[('checkin', 'Check In'), ('checkout', 'Check Out'), ('clean', 'Clean'), ('dirty', 'Dirty'), ('working', 'Working'), ('none', 'None')], max_length=13)),
                ('roominfo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.RoomInfo')),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='RateAtom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rateName', models.CharField(blank=True, max_length=512)),
                ('rateType', models.CharField(choices=[('standard', 'Standard'), ('deluxe', 'Deluxe'), ('pool_deluxe', 'Pool Deluxe'), ('lanai', 'Lanai'), ('presidential', 'Presidential'), ('manor', 'Manor'), ('SERVICE', 'SERVICE'), ('suites', 'Suites'), ('garden', 'Garden')], max_length=128)),
                ('lowSeason', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('highSeason', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('peakSeason', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('rateheading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.RateHeading')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clerk', models.CharField(max_length=40)),
                ('time', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=64)),
                ('desc', models.CharField(max_length=256)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('units', models.IntegerField(default=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='invoice',
            name='rateheading',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.RateHeading'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='rsvn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('pax', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('descr', models.TextField()),
                ('venue', models.CharField(choices=[('pool', 'Swimming Pool'), ('confroom2', 'Conference 2nd'), ('confroom3', 'Conference 3rd'), ('cafe', 'Cafe'), ('vcourt', 'Volleyball Court'), ('lobby', 'Lobby'), ('back', 'Back Space'), ('other', 'Other')], max_length=90)),
                ('dateStart', models.DateField()),
                ('timeStart', models.TimeField(default='00:00:00')),
                ('dateEnd', models.DateField()),
                ('timeEnd', models.TimeField(default='00:00:00')),
                ('rsvn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Rsvn')),
            ],
        ),
        migrations.CreateModel(
            name='AgentRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.Agent')),
                ('rateheading', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rsvn.RateHeading')),
            ],
        ),
    ]
